-- Drop child tables first
DROP TABLE IF EXISTS TripPhotos CASCADE;
DROP TABLE IF EXISTS Report CASCADE;
DROP TABLE IF EXISTS Review CASCADE;
DROP TABLE IF EXISTS Promote CASCADE;
DROP TABLE IF EXISTS GetReward CASCADE;
DROP TABLE IF EXISTS Messages CASCADE;
DROP TABLE IF EXISTS Blogs CASCADE;
DROP TABLE IF EXISTS Policies CASCADE;
DROP TABLE IF EXISTS Rewards CASCADE;
DROP TABLE IF EXISTS QA CASCADE;
DROP TABLE IF EXISTS Tickets CASCADE;
DROP TABLE IF EXISTS Trip CASCADE;
DROP TABLE IF EXISTS TravelAgency CASCADE;
DROP TABLE IF EXISTS Traveller CASCADE;
DROP TABLE IF EXISTS Admins CASCADE;
DROP TABLE IF EXISTS Users CASCADE;

-- Drop tables are now completed
